# Generated by Django 2.2 on 2019-04-13 11:33

import boilerplate.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_admission', models.DateTimeField(auto_now=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Nonbinary')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('due_date', models.DateTimeField(default=None, null=True)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('dealers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=boilerplate.models.create_dealer_list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SQL', 'SQL'), ('REDIS', 'Redis'), ('HTTP', 'HTTP')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('sources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boilerplate.Source')),
            ],
        ),
        migrations.CreateModel(
            name='OfferOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Success', 'S'), ('Fail', 'F'), ('Pending', 'P')], max_length=3)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_processed', models.DateTimeField(default=None, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boilerplate.Client')),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boilerplate.Dealer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boilerplate.Offer')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boilerplate.Dealer'),
        ),
    ]
