# Generated by Django 2.2 on 2019-04-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Nonbinary')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
