# Generated by Django 2.2 on 2019-04-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0002_source_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
