# Generated by Django 2.2 on 2019-04-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0002_auto_20190412_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
