# Generated by Django 2.2 on 2019-04-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0005_auto_20190412_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerorder',
            name='id_hash',
            field=models.CharField(max_length=64),
        ),
    ]
