# Generated by Django 2.2 on 2019-04-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0005_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='database',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
