# Generated by Django 2.2 on 2019-04-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0006_auto_20190412_2339'),
        ('boilerplate', '0006_source_database'),
    ]

    operations = [
    ]
