# Generated by Django 2.2 on 2019-04-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0007_merge_20190412_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerorder',
            old_name='result',
            new_name='status',
        ),
    ]
