# Generated by Django 2.2 on 2019-04-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0009_offer_dealers'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='sources',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='boilerplate.Source'),
            preserve_default=False,
        ),
    ]
