# Generated by Django 2.2 on 2019-04-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boilerplate', '0008_auto_20190413_0859'),
        ('boilerplate', '0010_auto_20190413_0840'),
    ]

    operations = [
    ]
